[package]
name = "rust_jcsql_sub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = "1.0.71"
lazy_static = "1.4.0"
odbc-api = "0.57.0"
oracle = "0.5.7"
